# Site settings
title: Juventude Empreendedora AL
email: your-email@domain.com
url: https://example.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
skills: "O projeto Juventude Empreendedora visa qualificar 5.000 jovens e adultos alagoanos, de 18 a 39 anos, preferencialmente que já concluíram ou estão concluindo o Ensino Médio e buscam montar o seu próprio negócio. Os cursos serão ministrados via internet, nos laboratórios de informática das escolas e telecentros participantes do projeto, sendo divididos em 5 módulos, cada um de 20h, totalizando 100h de formação. Os participantes do projeto terão a oportunidade de elaborar um plano de negócio e, se selecionados, poderão obter crédito para abrir sua empresa.
* Atenção! Visando abranger um público maior o projeto, que antes era destinado apenas à jovens de 18 a 29 anos, passou a contemplar adultos de 29 a 39 anos. É importante lembrar que até 30% das vagas são destinadas a faixa etária 29 a 39 anos, ou seja, cada turma pode ter até 30% de alunos da faixa etária 29 a 39 anos."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 221f1f #221f1f
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 221f1f #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Juventude Empreendedora 
  location: ACESSE
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: flickr
    url: http://flickr.com/
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
